name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devops-2023 -Dsonar.organization=devops-school -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2.7.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./httpd
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
